
[project]
name = "YanBot-infp"
version = "114514.1919810"
description = "QQOfficial SDK Bot"
authors = [
    {name = "ltzXiaoYanMo", email = "xiajiaruimail@qq.com"},
]
dependencies = [
    "qq-botpy>=1.1.2",
]
requires-python = ">=3.10"
license = {text = "MIT License"}
