
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "ltzXiaoYanMo", email = "2315049216@qq.com"},
]
dependencies = [
    "qq-botpy>=1.1.2",
]
requires-python = ">=3.10"
license = {text = "MIT License"}
